global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'galaos'
    environment: 'production'

# Alertmanager configuration (optional - add later)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "alerts/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # GalaOS API
  - job_name: 'galaos-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['galaos-api:4000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'galaos-api'

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # RabbitMQ
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  # Ollama (if it exposes metrics)
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
    metrics_path: '/metrics'

  # PyTorch Serving
  - job_name: 'pytorch-serve'
    static_configs:
      - targets: ['pytorch-serve:8082']

  # Qdrant
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: '/metrics'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Docker container metrics (via cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
