name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Build
        run: npm run build --if-present
      - name: Unit tests
        run: npm run test --if-present
      - name: Security audit
        run: npm run audit:ci || true

  e2e-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build workspace packages
        run: npm run build --if-present
      - name: Start web
        run: npm run start --workspace=@galaos/web &
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Wait for web
        run: npx -y wait-on http://localhost:3000
      - name: Run E2E tests
        run: npm run e2e
