name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build API image
        run: docker build -f apps/api/Dockerfile -t galaos-api:ci .
      - name: Build Web image
        run: docker build -f apps/web/Dockerfile -t galaos-web:ci .
