name: Security Audit

on:
  push:
    branches: [ main, master ]
  pull_request:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install
        run: npm ci
      - name: npm audit (fail on high/critical)
        run: npm run audit:ci
      - name: npm outdated (report only)
        run: |
          npm run outdated:ci | tee outdated.txt
      - name: Upload dependency report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-report
          path: |
            outdated.txt

